"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "bold green"

[character]
success_symbol = "[➜](bold blue)"
error_symbol = "[➜](bold red)"
vimcmd_symbol = "[<-](bold yellow)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = '([$all_status](218)[$ahead_behind](cyan)[$stashed](cyan) )'

conflicted = "*"
untracked = ""        
modified = "*"
staged = ""            
renamed = ""
deleted = ""
stashed = "≡"

ahead = "⇡"
behind = "⇣"
diverged = "⇡⇣"
up_to_date = ""

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []
